/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        // Custom PisoPilot colors from reference
        "surface-dim": "#dadadc",
        "outline-variant": "#bccabe",
        "tertiary-fixed": "#ffdad4",
        "on-secondary-fixed": "#181c1c",
        "inverse-on-surface": "#f0f0f3",
        "surface-container-high": "#e8e8ea",
        "primary-fixed-dim": "#59de9b",
        "tertiary": "#a43b2c",
        "on-primary-container": "#00331d",
        "primary-fixed": "#78fbb6",
        "surface-bright": "#f9f9fc",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#5d0601",
        "on-surface-variant": "#3d4a41",
        "on-surface": "#1a1c1e",
        "on-background": "#1a1c1e",
        "secondary-container": "#dde0df",
        "background": "#f9f9fc",
        "on-primary-fixed": "#002111",
        "on-secondary-fixed-variant": "#434847",
        "secondary": "#5b5f5f",
        "outline": "#6d7a70",
        "on-primary": "#ffffff",
        "inverse-primary": "#59de9b",
        "on-error-container": "#93000a",
        "primary-container": "#00a86b",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#c4c7c6",
        "on-tertiary-fixed-variant": "#842417",
        "surface-container-low": "#f3f3f6",
        "primary": "#006d43",
        "secondary-fixed": "#e0e3e2",
        "surface": "#f9f9fc",
        "surface-container": "#eeeef0",
        "on-error": "#ffffff",
        "tertiary-container": "#e86e5a",
        "surface-tint": "#006d43",
        "inverse-surface": "#2f3133",
        "surface-variant": "#e2e2e5",
        "tertiary-fixed-dim": "#ffb4a7",
        "surface-container-highest": "#e2e2e5",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#005232",
        "on-secondary-container": "#5f6363",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#400200",
        "error": "#ba1a1a",
        // ShadCN UI colors (keep for compatibility)
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "container-margin": "24px",
        gutter: "16px",
        "section-gap": "40px",
        "stack-md": "12px",
        "stack-sm": "4px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "display-currency": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-currency": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [],
}
